### ISSUE TITLE
code error in diamond of stars

### ISSUE THREAD

**Issue by Crazy-Naman** [itsjinendrajain/Coding-Ninjas-Problem-Solving-Using-Python#1]
### **new code**
`n=int(input())
if n%2!=0:
    n1 = (n+1)//2
    n2 = n//2
    i = 1
    while i <= n1:
        spaces = 1
        while spaces <= (n1-i):
            print(" ", end = "")
            spaces = spaces + 1
        j = 1
        while j <= (2*i) - 1:
            print("*", end = "")
            j = j+1
        print()
        i = i + 1
    i = n2
    while i >= 1:
        spaces = 1
        while spaces <= (n2 - i + 1):
            print(" ", end = "")
            spaces = spaces + 1
        j = 1
        while j<=(2*i)-1:
            print("*", end = "")
            j = j+1
        print()
        i = i-1 

- [ ] `

**Comment by itsjinendrajain** [comment]
You can Take help from my code, If you want help with your Code me send me your code in proper spaces in my telegram id https://t.me/chitkaranss
